@startuml
'https://plantuml.com/class-diagram
!include common-model-cd.puml

package org.iac2.checking {
    abstract class ComplianceIssue {
    }

    abstract class CheckingPlugin {
    + Collection<ComplianceIssue> findIssues(
    ComplianceRule, SystemModel, Collection<ComplianceRuleParameterAssignment>);
    }
    CheckingPlugin <|-- SubgraphIsomorphismCheckingPlugin
    CheckingPlugin <|-- LogicProgrammingCheckingPlugin

}

CheckingPlugin -up-> ComplianceRule
CheckingPlugin -up-> SystemModel
CheckingPlugin -up-> ComplianceRuleParameterAssignment
CheckingPlugin "1" -up-> "*" ComplianceIssue : produces


@enduml