@startuml
'https://plantuml.com/class-diagram

!include common-model-cd.puml
!include production-system-manager-cd.puml

package org.iac2.compliancejob {
    class ComplianceJobManager {
    }

    class ComplianceJob {

    }

    abstract class ComplianceJobTrigger
}




ComplianceJobManager "1" *-- "*" ComplianceJob: manages >
ComplianceJob "*" o-- "*" ComplianceJobTrigger
ComplianceJob "1" *-left- "*" ComplianceRuleParameterAssignment
ComplianceJob -> ProductionSystem : applies to
ComplianceJob --> ModelEnhancementStrategy : specifies
ComplianceJob --> FixingStrategy: specifies
ComplianceJob "*" *-left-"1" ComplianceRule
ComplianceJobManager "1" -> "*" ProductionSystemManager




@enduml