@startuml
'https://plantuml.com/class-diagram

!include common-model-cd.puml
package org.iac2.productionsystem {
    abstract class FixingPlugin {
    + Boolean fixIssue(ComplianceIssue, SystemModel, ProductionSystem)
    }
    class ProductionSystem
    class FixingStrategy
}



ComplianceIssue <-- FixingPlugin : fixes
SystemModel <-- FixingPlugin : gets info from
ProductionSystem <-- FixingPlugin : applies to
FixingStrategy o-- "*" FixingPlugin


@enduml