@startuml
'https://plantuml.com/class-diagram

!include common-model-cd.puml

package org.iac2.productionsystem {
    class ProductionSystemManager
    class ProductionSystem {
        id
    }
    abstract class ModelGenerationPlugin
    abstract class ModelEnhancementStrategy
    class FixingStrategy
}

class ProductionSystemManager {
+ SystemModel reconstructArchitecture()
+ Boolean fixIssue(ComplianceIssue, SystemModel)
}

SystemModel "*" <-- ProductionSystemManager : generates
ProductionSystem --o ProductionSystemManager
ModelEnhancementStrategy "*" <-- ProductionSystemManager : executes
ModelGenerationPlugin --o ProductionSystemManager
ComplianceIssue "*" <-- ProductionSystemManager: fixes
FixingStrategy "*" <-- ProductionSystemManager: executes


@enduml