version: '3.7'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iac2
      MYSQL_PASSWORD: rootpassword
      MYSQL_USER: iac2-admin
    ports:
      - '4406:3306'
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  winery-cr-modeling:
    image: opentosca/winery
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      WINERY_FEATURE_EDMM_MODELING: "true"
      WINERY_FEATURE_TEST_COMPLIANCE: "true"
      WINERY_FEATURE_UPDATE_TEMPLATES: "true"
      WINERY_REPOSITORY_URL: "https://github.com/IAC2-Project/compliance-rule-modeling-repository"
    ports:
      - '8080:8080'
    volumes:
      - cr_modeling:/var/repository
  winery-im-modeling:
    image: opentosca/winery
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      WINERY_FEATURE_EDMM_MODELING: "true"
      WINERY_FEATURE_UPDATE_TEMPLATES: "true"
      WINERY_REPOSITORY_URL: "https://github.com/IAC2-Project/instance-model-modeling-repository"
    ports:
      - '7070:8080'
    volumes:
      - im_modeling:/var/repository
  engine-ia-java8:
    image: opentosca/engine-ia:latest-jdk8
    ports:
      - '8098:8080'
  engine-ia-java17:
    image: opentosca/engine-ia:latest-jdk17
    ports:
      - '8099:8080'
  engine-plan:
    image: opentosca/ode:latest
    environment:
      _JAVA_OPTIONS: "-Xmx3048m -Xms512m -Xss4m"
    ports:
      - '9763:9763'
  engine-plan-bpmn:
    image: opentosca/camunda-bpmn:latest
    ports:
      - '8092:8080'
  container:
    image: opentosca/container:latest
    ports:
      - '1337:1337'
      - '1883:1883' # MQTT
      - '8081-8083:8081-8083'
      - '8085-8087:8085-8087'
    environment:
      CONTAINER_HOSTNAME: ${PUBLIC_HOSTNAME}
      ENGINE_IA_HOSTNAME: ${PUBLIC_HOSTNAME}
      ENGINE_IA_PORT: 8098
      ENGINE_IA_JAVA17_HOSTNAME: ${PUBLIC_HOSTNAME}
      ENGINE_IA_JAVA17_PORT: 8099
      ENGINE_PLAN_BPEL_HOSTNAME: ${PUBLIC_HOSTNAME}
      ENGINE_PLAN_BPMN_HOSTNAME: ${PUBLIC_HOSTNAME}
      ENGINE_PLAN_BPMN_PORT: 8092
      CONTAINER_DEPLOYMENT_TESTS: 'false'
    volumes:
      - container_vol:/tmp/opentosca
  ui:
    image: opentosca/ui:latest
    environment:
      API_ENDPOINT_HOST: ${PUBLIC_HOSTNAME}
      API_ENDPOINT_PORT: 1337
      WINERY_HOST: ${PUBLIC_HOSTNAME}
      WINERY_PORT: 7070
    ports:
      - '8088:8080'
volumes:
  mysql_db_data_container: {}
  cr_modeling: {}
  im_modeling: {}
  container_vol: {}



