@startuml
'https://plantuml.com/component-diagram

[Job Manager]

getRuleImplementation -left- [Modeling]

findIssues -- [Checking]

reconstructArchitecture -- [Production System Manager]

fixIssue -- [Production System Manager]

[Job Manager] -left-> getRuleImplementation

[Job Manager] --> findIssues

[Job Manager] --> reconstructArchitecture
[Job Manager] --> fixIssue

@enduml